#!/bin/bash

layout=""
capacity=""
timedate=""
status=""
brightness=""
volume=""
cpu_temp=""
dns=""

get_layout() {
kb=$(xset -q | grep -oP '\d{8}')

  case $kb in
    "00001000")
    layout="ru"
    ;;
    "00000000")
    layout="en"
    ;;
  esac
}

battery() {
    capacity="$(cat /sys/class/power_supply/BAT0/capacity)%"
    status="$(cat /sys/class/power_supply/BAT0/status)"
}

timedate() {
    timedate=$(timedatectl | awk '/Local time:/ {print $3, $4, $5, $6, $7}')
}

brightness() {
    brightness=$(cat /sys/class/backlight/amdgpu_bl1/brightness)
}

volume() {
    volume=$(amixer sget Master | awk '/Front Left:/ {print $5 $6}')
}

cpu_temp() {
    cpu_temp=$(sensors | awk '/CPU:/ {printf $2}')
}

dns() {
    dns=$(nmcli dev show | awk '/IP4.DNS\[1\]/ {print $2}')
}

i3status | while :
do
  read line
  get_layout
  battery
  brightness
  timedate
  volume
  cpu_temp
  dns
  echo "$layout | dns: $dns | cpu: $cpu_temp | volume: $volume | brightness: $brightness | $capacity $status | $timedate | $line" || exit 1
done
